/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author halim
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form ElevatorGUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Building1 = new javax.swing.JPanel();
        CallFromFloor6 = new javax.swing.JButton();
        CallFromFloor5 = new javax.swing.JButton();
        CallFromFloor4 = new javax.swing.JButton();
        CallFromFloor3 = new javax.swing.JButton();
        CallFromFloor2 = new javax.swing.JButton();
        CallFromFloor1 = new javax.swing.JButton();
        Elevator = new javax.swing.JPanel();
        Led = new javax.swing.JPanel();
        Image = new javax.swing.JLabel();
        ButtonsPanel = new javax.swing.JPanel();
        RequestToFloor1 = new javax.swing.JButton();
        RequestToFloor2 = new javax.swing.JButton();
        RequestToFloor3 = new javax.swing.JButton();
        RequestToFloor4 = new javax.swing.JButton();
        RequestToFloor5 = new javax.swing.JButton();
        RequestToFloor6 = new javax.swing.JButton();
        OpenDoorBtn = new javax.swing.JButton();
        CloseDoorBtn = new javax.swing.JButton();
        EmergencyBtn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Building1.setBackground(new java.awt.Color(255, 255, 255));
        Building1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CallFromFloor6.setBackground(new java.awt.Color(255, 255, 255));
        CallFromFloor6.setText("Call");
        CallFromFloor6.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                CallFromFloor6HierarchyChanged(evt);
            }
        });
        CallFromFloor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallFromFloor6ActionPerformed(evt);
            }
        });
        CallFromFloor6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CallFromFloor6PropertyChange(evt);
            }
        });
        Building1.add(CallFromFloor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, 41));

        CallFromFloor5.setBackground(new java.awt.Color(255, 255, 255));
        CallFromFloor5.setText("Call");
        CallFromFloor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallFromFloor5ActionPerformed(evt);
            }
        });
        Building1.add(CallFromFloor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 41));

        CallFromFloor4.setBackground(new java.awt.Color(255, 255, 255));
        CallFromFloor4.setText("Call");
        CallFromFloor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallFromFloor4ActionPerformed(evt);
            }
        });
        Building1.add(CallFromFloor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 271, 60, 41));

        CallFromFloor3.setBackground(new java.awt.Color(255, 255, 255));
        CallFromFloor3.setText("Call");
        CallFromFloor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallFromFloor3ActionPerformed(evt);
            }
        });
        Building1.add(CallFromFloor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 60, 41));

        CallFromFloor2.setBackground(new java.awt.Color(255, 255, 255));
        CallFromFloor2.setText("Call");
        CallFromFloor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallFromFloor2ActionPerformed(evt);
            }
        });
        Building1.add(CallFromFloor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 60, 41));

        CallFromFloor1.setBackground(new java.awt.Color(255, 255, 255));
        CallFromFloor1.setText("Call");
        CallFromFloor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallFromFloor1ActionPerformed(evt);
            }
        });
        Building1.add(CallFromFloor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 60, 41));

        Elevator.setBackground(new java.awt.Color(0, 153, 255));
        Elevator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Led.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout LedLayout = new javax.swing.GroupLayout(Led);
        Led.setLayout(LedLayout);
        LedLayout.setHorizontalGroup(
            LedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        LedLayout.setVerticalGroup(
            LedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Elevator.add(Led, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, -1));

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/opened.png"))); // NOI18N
        Elevator.add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        Building1.add(Elevator, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 50, 60));

        ButtonsPanel.setBackground(new java.awt.Color(219, 217, 208));

        RequestToFloor1.setText("1");
        RequestToFloor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestToFloor1ActionPerformed(evt);
            }
        });

        RequestToFloor2.setText("2");
        RequestToFloor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestToFloor2ActionPerformed(evt);
            }
        });

        RequestToFloor3.setText("3");
        RequestToFloor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestToFloor3ActionPerformed(evt);
            }
        });

        RequestToFloor4.setText("4");
        RequestToFloor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestToFloor4ActionPerformed(evt);
            }
        });

        RequestToFloor5.setText("5");
        RequestToFloor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestToFloor5ActionPerformed(evt);
            }
        });

        RequestToFloor6.setText("6");
        RequestToFloor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestToFloor6ActionPerformed(evt);
            }
        });

        OpenDoorBtn.setText("Open Door");
        OpenDoorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenDoorBtnActionPerformed(evt);
            }
        });

        CloseDoorBtn.setText("Close Door");
        CloseDoorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseDoorBtnActionPerformed(evt);
            }
        });

        EmergencyBtn.setText("Emergency");
        EmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RequestToFloor5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(RequestToFloor3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(RequestToFloor1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RequestToFloor4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(RequestToFloor6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(RequestToFloor2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(OpenDoorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(CloseDoorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(EmergencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RequestToFloor2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(RequestToFloor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RequestToFloor3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RequestToFloor4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RequestToFloor5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RequestToFloor6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OpenDoorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseDoorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmergencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        Building1.add(ButtonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 320));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg.jpg"))); // NOI18N
        Building1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Building1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Building1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CallFromFloor6HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_CallFromFloor6HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CallFromFloor6HierarchyChanged

    private void CallFromFloor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallFromFloor6ActionPerformed
        TranslateTo(6);
    }//GEN-LAST:event_CallFromFloor6ActionPerformed

    private void CallFromFloor6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CallFromFloor6PropertyChange

    }//GEN-LAST:event_CallFromFloor6PropertyChange

    private void CallFromFloor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallFromFloor1ActionPerformed
        TranslateTo(1);
    }//GEN-LAST:event_CallFromFloor1ActionPerformed

    private void RequestToFloor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestToFloor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestToFloor1ActionPerformed

    private void RequestToFloor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestToFloor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestToFloor2ActionPerformed

    private void RequestToFloor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestToFloor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestToFloor3ActionPerformed

    private void RequestToFloor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestToFloor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestToFloor4ActionPerformed

    private void RequestToFloor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestToFloor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestToFloor5ActionPerformed

    private void RequestToFloor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestToFloor6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestToFloor6ActionPerformed

    private void OpenDoorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenDoorBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenDoorBtnActionPerformed

    private void CloseDoorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseDoorBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseDoorBtnActionPerformed

    private void EmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmergencyBtnActionPerformed

    private void CallFromFloor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallFromFloor5ActionPerformed
        TranslateTo(5);
    }//GEN-LAST:event_CallFromFloor5ActionPerformed

    private void CallFromFloor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallFromFloor4ActionPerformed
        TranslateTo(4);
    }//GEN-LAST:event_CallFromFloor4ActionPerformed

    private void CallFromFloor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallFromFloor3ActionPerformed
        TranslateTo(3);
    }//GEN-LAST:event_CallFromFloor3ActionPerformed

    private void CallFromFloor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallFromFloor2ActionPerformed
        TranslateTo(2);
    }//GEN-LAST:event_CallFromFloor2ActionPerformed

    
    private void TranslateTo(int FloorNumber) {

        int FloorIndex = FloorNumber-1;
        float [] FloorY = {590,470,360,250,150,55};
        while (Math.abs(Elevator.getLocation().y - FloorY[FloorIndex]) > 10) {
            if (Elevator.getLocation().y > FloorY[FloorIndex]) {
                Elevator.setLocation(Elevator.getLocation().x, Elevator.getLocation().y - 10);
            } else {
                Elevator.setLocation(Elevator.getLocation().x, Elevator.getLocation().y + 10);
            } 
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Building;
    private javax.swing.JPanel Building1;
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton Call6;
    private javax.swing.JButton CallFromFloor1;
    private javax.swing.JButton CallFromFloor2;
    private javax.swing.JButton CallFromFloor3;
    private javax.swing.JButton CallFromFloor4;
    private javax.swing.JButton CallFromFloor5;
    private javax.swing.JButton CallFromFloor6;
    private javax.swing.JButton CloseDoorBtn;
    private javax.swing.JPanel Elevator;
    private javax.swing.JButton EmergencyBtn;
    private javax.swing.JLabel Image;
    private javax.swing.JPanel Led;
    private javax.swing.JButton OpenDoorBtn;
    private javax.swing.JButton RequestToFloor1;
    private javax.swing.JButton RequestToFloor2;
    private javax.swing.JButton RequestToFloor3;
    private javax.swing.JButton RequestToFloor4;
    private javax.swing.JButton RequestToFloor5;
    private javax.swing.JButton RequestToFloor6;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
